<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Copyright>Copyright ©, Ltd</Copyright>
    <Authors>MindWebTree</Authors>
    <PackageLicenseUrl></PackageLicenseUrl>
	  <OutputPath>..\..\Presentation\Nop.Web\Plugins\MWT.Plugin.Misc.MwtStorefront</OutputPath>
    <OutDir>$(OutputPath)</OutDir>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Migrations\**" />
    <Compile Remove="Models\Seo\**" />
    <Compile Remove="PackageFiles\**" />
    <EmbeddedResource Remove="Migrations\**" />
    <EmbeddedResource Remove="Models\Seo\**" />
    <EmbeddedResource Remove="PackageFiles\**" />
    <None Remove="Migrations\**" />
    <None Remove="Models\Seo\**" />
    <None Remove="PackageFiles\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="logo.jpg" />
    <None Remove="plugin.json" />
    <None Remove="Views\_ViewImports.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="logo.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="plugin.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
	  <Content Include="Views\**\*.cshtml">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Areas\Admin\Views\**\*.cshtml">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Content\**\*">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
  </ItemGroup>

	<ItemGroup>
		<ClearPluginAssemblies Include="$(MSBuildProjectDirectory)\..\..\Build\ClearPluginAssemblies.proj" />
	</ItemGroup>

  <ItemGroup>
    <Content Include="logo.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\_ViewImports.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="30.0.1" />
  </ItemGroup>

	<ItemGroup>
		
		<ProjectReference Include="..\..\MWT.Nop.Core\MWT.Nop.Core.csproj" />
		
		<ProjectReference Include="..\..\Presentation\Nop.Web\Nop.Web.csproj" /> 
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Factories\Api\" />
	</ItemGroup>

	 


  <!-- This target execute after "Build" target -->
  <Target Name="NopTarget" AfterTargets="Build">
    <!-- Delete unnecessary libraries from plugins path -->
    <MSBuild Projects="@(ClearPluginAssemblies)" Properties="PluginPath=$(MSBuildProjectDirectory)\$(OutDir)" Targets="NopClear" />
  </Target>

</Project>
